=== smwkerofin/ROXApps/Apps/AppFactory/Resources/AppInfo.dtd
<!-- DTD for ROX AppInfo files -->

<!-- In AppInfo we have 3 optional elements. -->
<!ELEMENT AppInfo (About?,Summary?,AppMenu?)>

<!ELEMENT About (Purpose?,Version?,Authors?,License?,Homepage?)>
<!ELEMENT Purpose (#PCDATA)>
<!ELEMENT Version (#PCDATA)>
<!ELEMENT Authors (#PCDATA)>
<!ELEMENT License (#PCDATA)>
<!ELEMENT Homepage (#PCDATA)>

<!ELEMENT Summary (#PCDATA)>

<!ELEMENT AppMenu (Item|AppMenu)+>
<!ELEMENT Item EMPTY>
<!ATTLIST Item label CDATA #REQUIRED>
<!ATTLIST Item option CDATA #REQUIRED>

=== smwkerofin/ROXApps/lib/ROX-CLib/AppInfo.xml
<?xml version="1.0"?>
<!DOCTYPE AppInfo SYSTEM "/home/stephen/src/rox/AppInfo.dtd">
<AppInfo>
  <About>
    <Purpose>C library for ROX apps</Purpose>
        <Version>0.1.10 (13 February 2002)</Version>
    <Authors>Stephen Watson, Thomas Leonard</Authors>
    <License>GNU General Public License</License>
    <Homepage>http://www.kerofin.demon.co.uk/rox/</Homepage>
  </About>
  <Summary>C library for ROX apps</Summary>
<AppMenu>
  <Item label="Compile library" option="--compile"/>
</AppMenu>
</AppInfo>
